name: Scheduled Scan
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install ecdsa base58 requests
      - name: Run scanner
        run: python scanner.py >> scan.log
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: |
            found.txt
            scan.log
